class Searches{getSearches(){return null!==localStorage.getItem("searches")&&JSON.parse(localStorage.getItem("searches"))}pushSearches(e){if(e=e.replaceAll("<","&#60;").replaceAll(">","&#62").replaceAll("'","&apos;").replaceAll('"',"&quot;").replaceAll("\\","&#92;"),null==localStorage.getItem("searches")){let a=JSON.stringify([e]);localStorage.setItem("searches",a)}else{let s=JSON.parse(localStorage.getItem("searches"));s.unshift(e),localStorage.setItem("searches",JSON.stringify(s))}}clearSearches(){localStorage.setItem("searches",JSON.stringify([])),_id("header-search-queries").innerHTML='<p class="text-center font-default">No recent searches</p>',_id("header-search-input").focus()}constructor(){this.container=""}openSearches(){let e=this.getSearches(),a="",s="";e&&0!=e.length?(e.forEach(e=>{a+=`<a href="/search?query=${e}" class="Header-search-query">${e.replaceAll("+"," ")}</a>`}),s='<button id="header-clear-searches" class="btn-classic btn-classic-blue">Clear All</button>'):(a='<p class="text-center font-default">No recent searches</p>',s=""),this.container=document.createElement("div"),this.container.setAttribute("class","Header-search-container"),this.container.innerHTML=`<div class="Header-search-panel">
        <form class="Header-search-panel-items" id="header-form" autocomplete="off">
            <svg xmlns="http://www.w3.org/2000/svg" class="Header-search-panel-icon me-2" width="64" height="64" viewBox="0 0 64 64"><rect width="64" height="64" fill="none"/><path d="M57.2,56.7,47.9,45.1a23,23,0,0,0,2.8-3.4A24.9,24.9,0,0,0,43.9,7.1,24.9,24.9,0,0,0,5.6,32.6,25,25,0,0,0,30,52.7a28.1,28.1,0,0,0,4.9-.5,22.7,22.7,0,0,0,7.5-2.8l9.3,11.7a3.5,3.5,0,0,0,2.8,1.4,4,4,0,0,0,2.2-.8A3.6,3.6,0,0,0,57.2,56.7ZM33.5,45.3a17.9,17.9,0,0,1-21-14,18,18,0,0,1,2.7-13.4,17.7,17.7,0,0,1,11.4-7.6A19.5,19.5,0,0,1,30,10,17.8,17.8,0,0,1,47.5,24.3a17.5,17.5,0,0,1-2.6,13.4,19.5,19.5,0,0,1-3.6,4l-.4.2-.3.3A18.1,18.1,0,0,1,33.5,45.3Z"/></svg>
            <input class="Header-search-panel-input" id="header-search-input" placeholder="Search BracketCounters...">
        </form>
        <div class="Header-search-queries my-2" id="header-search-queries">
            ${a}
        </div>
        ${s}
    </div>`,document.body.appendChild(this.container),document.body.classList.add("overflow-hidden"),_id("header-search-input").focus(),_id("header-form").addEventListener("submit",e=>{e.preventDefault();let a=_id("header-search-input").value.replaceAll(" ","+");""!=a&&(this.pushSearches(a),window.open(`/search?query=${a}`,"_self").focus())}),_id("header-clear-searches")&&_id("header-clear-searches").addEventListener("click",e=>{e.target.style.display="none",this.clearSearches()}),window.addEventListener("click",e=>{e.target.parentNode==document.body&&(document.body.removeChild(this.container),document.body.classList.remove("overflow-hidden"))})}}
